# Generated by Django 4.2 on 2024-06-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_user_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
