# Generated by Django 4.2 on 2024-06-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_usuario_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='phone',
            new_name='telefono',
        ),
    ]
