# Generated by Django 4.2 on 2024-06-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
