# Generated by Django 4.2 on 2024-05-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0002_categoria_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='musculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ejerciciomusculo',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ejercicio.ejercicio'),
        ),
        migrations.AlterField(
            model_name='ejerciciomusculo',
            name='musculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ejercicio.musculo'),
        ),
    ]
