# Generated by Django 4.2 on 2024-06-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0003_ejercicio_activo_musculo_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios', to='ejercicio.categoria'),
        ),
    ]
