# Generated by Django 4.2 on 2024-06-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0004_alter_ejercicio_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='imagen',
        ),
    ]
