# Generated by Django 4.2 on 2024-06-05 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0005_remove_ejercicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios', to='ejercicio.categoria'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
