# Generated by Django 4.2 on 2024-06-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_alter_actividad_ejercicio_alter_serie_actividad'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadespordia',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_dia', to='actividad.actividad'),
        ),
        migrations.AlterField(
            model_name='actividadespordia',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_actividad', to='plan.diaplan'),
        ),
        migrations.AlterField(
            model_name='diaplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_plan', to='plan.plan'),
        ),
    ]
