# Generated by Django 4.2 on 2024-06-05 12:42

from django.db import migrations, models
import django.db.models.deletion
import plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_delete_token'),
        ('plan', '0002_alter_actividadespordia_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='usuario.usuario'),
        ),
        migrations.CreateModel(
            name='AlumnoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_asociados', to='usuario.usuario')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='plan.plan')),
            ],
            bases=(models.Model, plan.models.ModeloBase),
        ),
    ]
