# Generated by Django 4.2 on 2024-06-05 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_diaplan_activo_plan_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='fechaInicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
