# Generated by Django 4.2 on 2024-06-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0004_alter_ejercicio_categoria'),
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='ejercicio.ejercicio'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='actividad.actividad'),
        ),
    ]
