# Generated by Django 4.2 on 2024-06-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_alter_actividad_ejercicio_alter_serie_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
