# Generated by Django 4.2 on 2024-06-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0006_alter_ejercicio_categoria_and_more'),
        ('actividad', '0003_actividad_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='ejercicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='ejercicio.ejercicio'),
        ),
    ]
