# Generated by Django 4.2 on 2024-06-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0004_alter_actividad_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
